#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install Debugging Tools
  hosts: Ubuntu
  become: True
  tasks:
      - hostname: name=charlie
      - pip: name=httpie

- name: Start Docker Containers
  hosts: Ubuntu
  become: False
  vars:
       charlie_ip: "10.10.10.30"

       rabbitmq_user: "guest"
       rabbitmq_password: "guest"
       rabbitmq_vhost: "/"

       reporting_exchange: "exchange-events"
       reporting_database: "reporting"

       report_event_processor_image_tag: "1.0.768.MILESTONE"
       report_event_processor_http_port: "3080"
       report_event_processor_jmx_port: "3020"

       replay_image_tag: "1.1.49.MILESTONE"
       replay_http_port: "4080"
       replay_jmx_port: "4020"
       replay_database: "journal"

  tasks:
      - name: MongoDB
        docker_container:
            command: "--storageEngine=wiredTiger --wiredTigerCacheSizeGB=1 --directoryperdb"
            detach: True
            hostname: "mongodb"
            image: "mongo:latest"
            log_driver: "json-file"
            log_options:
                max-size: "50m"
            name: "mongodb"
            network_mode: "host"
            restart_policy: "always"
            state: "started"
            trust_image_content: True

      - name: RabbitMQ
        docker_container:
            detach: True
            env:
                RABBITMQ_DEFAULT_USER: "{{ rabbitmq_user }}"
                RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_password }}"
                RABBITMQ_DEFAULT_VHOST: "{{ rabbitmq_vhost }}"
            hostname: "rabbitmq"
            image: "rabbitmq:management"
            log_driver: "json-file"
            log_options:
                max-size: "50m"
            # limit RabbitMQ to 1GB of RAM or it will steal 40% of available memory
            memory: "1GB"
            name: "rabbitmq"
            network_mode: "host"
            restart_policy: "always"
            state: "started"
            trust_image_content: True

      - name: Mold-E Event Processor
        docker_container:
            detach: True
            env:
                SPRING_PROFILES_ACTIVE: "default"
                LFS_DOMAIN_NAME: "dumb"
                JVM_HEAP_MIN: "256m"
                JVM_HEAP_MAX: "256m"
                JVM_JMX_HOST: "{{ charlie_ip }}"
                JVM_JMX_PORT: "{{ report_event_processor_jmx_port }}"
                JVM_JMX_RMI_PORT: "{{ report_event_processor_jmx_port }}"
                mold-e_rabbitExchangeName: "{{ reporting_exchange }}"
                spring_rabbitmq_host: "rabbitmq"
                spring_rabbitmq_virtual-host: "{{ rabbitmq_vhost }}"
                spring_rabbitmq_username: "{{ rabbitmq_user }}"
                spring_rabbitmq_password: "{{ rabbitmq_password }}"
                spring_data_mongodb_host: "mongodb"
                spring_data_mongodb_database: "{{ reporting_database }}"
            etc_hosts:
                mongodb: "{{ charlie_ip }}"
                rabbitmq: "{{ charlie_ip }}"
            hostname: "event-processor"
            image: "registry.transparent.com/mold-e-reporting-event-processor:{{ report_event_processor_image_tag }}"
            log_driver: "json-file"
            log_options:
                max-size: "50m"
            name: "event-processor"
            network_mode: "bridge"
            published_ports:
            - "{{ report_event_processor_http_port }}:8080"
            - "{{ report_event_processor_jmx_port }}:2020"
            pull: False
            restart_policy: "always"
            state: "started"
            trust_image_content: True

      - name: Replay Tool
        docker_container:
            detach: True
            env:
                SPRING_PROFILES_ACTIVE: "default"
                LFS_DOMAIN_NAME: "dumb"
                JVM_HEAP_MIN: "256m"
                JVM_HEAP_MAX: "256m"
                JVM_JMX_HOST: "{{ charlie_ip }}"
                JVM_JMX_PORT: "{{ replay_jmx_port }}"
                JVM_JMX_RMI_PORT: "{{ replay_jmx_port }}"
                mold-e_rabbitExchangeName: "{{ reporting_exchange }}"
                spring_rabbitmq_host: "rabbitmq"
                spring_rabbitmq_virtual-host: "{{ rabbitmq_vhost }}"
                spring_rabbitmq_username: "{{ rabbitmq_user }}"
                spring_rabbitmq_password: "{{ rabbitmq_password }}"
                spring_data_mongodb_host: "mongodb"
                spring_data_mongodb_database: "{{ replay_database }}"
                replay_processor_port: "{{ report_event_processor_http_port }}"
            etc_hosts:
                mongodb: "{{ charlie_ip }}"
                rabbitmq: "{{ charlie_ip }}"
                mold-e: "{{ charlie_ip }}"
            hostname: "batch-replay"
            image: "registry.transparent.com/mold-e-replay:{{ replay_image_tag }}"
            log_driver: "json-file"
            log_options:
                max-size: "50m"
            name: "batch-replay"
            network_mode: "bridge"
            published_ports:
            - "{{ replay_http_port }}:8080"
            - "{{ replay_jmx_port }}:2020"
            pull: False
            restart_policy: "always"
            state: "started"
            trust_image_content: True

